Procfile
app/main.py
requirements.txt
wsgi.py

Implementa a rota de hello world

---

app/main.py
wsgi.py

Avaliar as alterações e, caso tudo ok, mergear na main

crud após alterações de conflito

---

app/app.py
app/controllers/usuario_controller.py
app/models/usuario.py
app/rotas.py

atualizando cadastro para modelo MVC

---

wsgi.py

conserta o crash do app por conta do wsgi

---

wsgi.py

conserta o erro da porta errada, usa a porta dada pelo heroku

---

Procfile
wsgi.py

dá o bind da porta do heroku no comando do gunicorn

---

wsgi.py

fix wsgi.py

---

app/controllers/usuario_controller.py
wsgi.py

Bugfix: Resolvido erro de confirmação email/senha

---

app/app.py
app/controllers/usuario_controller.py
app/rotas.py

Usa a forma imperativa no lugar de decorators para declarar rotas

---

app/controllers/usuario_controller.py

Bugfix: Retorno de erros padronizado numa unica lista

---

requirements.txt

Adicionar PyJWT no requirements

---

app/controllers/usuario_controller.py
app/rotas.py

Refatora validar_body e a torna genérica para uso em outras rotas

---

app/config.py
app/controllers/usuario_controller.py
app/models/usuario.py
app/utils/auth.py

Recebimento steam

---

app/controllers/usuario_controller.py

Ajusta retorno da rota auth_steam_delete

---

app/config.py
app/controllers/usuario_controller.py
app/rotas.py
app/views/usuario_view.py
requirements.txt

Listar jogos steam

---

app/views/usuario_view.py

ordenando alfabeticamente o retorno da função listar jogos steam

---

app/controllers/usuario_controller.py

Ajuste nos retornos da validar_body

---

app/controllers/usuario_controller.py

Reverte mudanças na validação, corrigindo um bug em produção

---

app/controllers/usuario_controller.py

Remove validar senha no momento do login

---

app/controllers/usuario_controller.py

Ajusta Regex da senha e limita tamanho.

---

app/controllers/usuario_controller.py

Melhorias esqueci senha

---

app/models/usuario.py

Remove espaço no inicio e fim do nome ao salvar

---

.githooks.ini
requirements-dev.txt

Adiciona Githooks no projeto

---

app/utils/logger_test.py

Adiciona testes para a classe Logger

---

.githooks.ini
.githooks/pre-commit.sh
.githooks/pre-push.sh
.github/workflows/pull_request.yml
app/app.py
app/controllers/usuario_controller.py
app/models/usuario.py
app/rotas.py
app/utils/auth.py
app/utils/logger.py
app/utils/logger_test.py
app/views/usuario_view.py
wsgi.py

Conserta os erros do Pylint

---

app/controllers/usuario_controller.py
app/controllers/usuario_controller_test.py
app/rotas.py
requirements-dev.txt

implementando pytest na rota esqueci-senha

---

app/controllers/usuario_controller_test.py

Validar body test

---

.editorconfig
app/controllers/usuario_controller.py
app/controllers/usuario_controller_test.py
app/rotas.py
app/utils/auth.py
wsgi.py

Adicionar testes na rota auth_steam

---

app/app.py
app/config.py
app/services/jogo_services.py
wsgi.py

Conserta as variáveis de ambiente quando rodamos o projeto com o gunicorn

---

app/views/jogo_view.py
app/views/jogo_view_test.py

Cria teste unitário para serializar_jogos

---

app/utils/auth.py
app/utils/auth_test.py

Cria testes para função token_required

---

app/utils/validacoes.py
app/utils/validacoes_test.py

Revisao regex senha email

---

app/config.py
app/controllers/jogo_controller.py
app/rotas.py
app/services/jogo_services.py
app/services/jogo_services_test.py
app/views/jogo_view.py

Detalhes jogo steam

---

app/app.py
requirements.txt

Adiciona cors a api

---

scripts/pylint.sh

Remove os arquivos de migration da verificacao com pylint

---

app/models/usuario.py
app/services/usuario_services.py
app/services/usuario_services_test.py
app/utils/validacoes.py
app/utils/validacoes_test.py

Melhorias validar body

---

app/utils/validacoes.py

Corrige logica de minimo de caractere
